version: '3.2'
services:
  mdsplus:
    # image: 'ras-mdsplus:latest'
    build:
      context: ./
      dockerfile: docker/mdsplus/Dockerfile
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/.Xauthority
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
    - ./mdsplus/trees:/trees:rw
    - ./mdsplus/config/envsyms:/usr/local/mdsplus/local/envsyms:rw
    - ./mdsplus/epics:/usr/local/mdsplus/epics:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
