version: '3.2'
services:
  mdsplus-tree:
    build:
      context: ./
      dockerfile: docker/mdsplus/mdsplus-tree.dockerfile
      # dockerfile: docker/mdsplus/mdsplus-app.dockerfile
    restart: always
    volumes:
      - ./mdsplus/trees:/trees:rw
      - ./mdsplus/config/envsyms:/usr/local/mdsplus/local/envsyms:rw
      # - ./docker/caddy/supervisord_mds.conf:/etc/supervisor/conf.d/supervisord_mds.conf
      - /dev/shm:/dev/shm
    ports:
      - "6081:80"
    # network_mode: host
    # environment:
    #   - HTTP_PASSWORD=Ignition!
    #   - RESOLUTION=1920x1080