version: '3.2'
services:
  mdsplus-archiver:
    build:
      context: ./
      dockerfile: docker/mdsplus/mdsplus-epics-archiver.dockerfile
    restart: always
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./mdsplus/trees:/trees:rw
      - ./mdsplus/config/envsyms:/usr/local/mdsplus/local/envsyms:rw
      - .mdsplus/epics:/usr/local/mdsplus/local/epics:rw
      # - /dev/shm:/dev/shm
    # ports:
    #   - "6081:80"
    network_mode: host
    # environment:
    #   - HTTP_PASSWORD=Ignition!
    #   - RESOLUTION=1920x1080