version: '3.2'
services:
    
  mdsplus-caddy:
    build:
      context: ./
      dockerfile: docker/caddy/mdsplus-caddy.dockerfile
    restart: always
    network_mode: "host"
    # environment: 
    #   - APP_USERNAME=operator
    #   - APP_PASSWORD_HASH=JDJhJDEwJFZZdXVhMjVzQnBJbzJYREVDeTA1V09QVHNGVWZlSVJROUlHNHM3MC55cnh6Lkx1RmJRa2dP