version: '3.2'
services:
  mdsplus-tree:
    build:
      context: ./
      dockerfile: docker/mdsplus/mdsplus-ubuntu.dockerfile
    restart: always
    volumes:
      - ./mdsplus/trees:/trees:rw
      - ./mdsplus/config/envsyms:/usr/local/mdsplus/local/envsyms:rw
      - /dev/shm:/dev/shm
    ports:
      - "6081:80"
    # network_mode: host
    environment:
      - HTTP_PASSWORD=Ignition!
      - RESOLUTION=1920x1080